// Offline creation draft: exercises real controls without submitting a character.
ui.waitForFrame("CharCreateNext", 10.0);
ui.click("Race_1");
ui.click("Class_1");
ui.click("CharCreateSex_1");
ui.click("CharCreateSex_0");
ui.click("CharCreateNext");
ui.waitForFrame("Category_23", 10.0);
ui.click("Category_23");
ui.waitForFrame("OptionToggle_8789", 10.0);
ui.click("OptionToggle_8789");
ui.waitForFrame("OptionChoice_8789_56652", 10.0);
ui.click("OptionChoice_8789_56652");
ui.click("Category_3");
ui.waitForFrame("OptionToggle_463", 10.0);
ui.click("OptionToggle_463");
ui.waitForFrame("OptionChoice_463_4127", 10.0);
ui.click("OptionChoice_463_4127");
ui.click("CharCreateNameInput");
ui.type("DraftProof");
ui.click("Camera_zoom_in");
ui.click("Camera_rotate_left");
ui.click("Camera_reset");
ui.click("CharCreateBack");
ui.waitForFrame("CharCreateNext", 10.0);
ui.click("CharCreateNext");
ui.waitForFrame("Category_23", 10.0);
ui.click("Category_23");
ui.waitForFrame("Option_8789", 10.0);
