# Local Retail 12.1.0.69933. WoWDBDefs definitions/<table>.dbd exact build layouts.
# Numeric columns only; omitted floats/strings still occupy their authored field indices.
CLOSURE_TABLES = {
    "BarrageEffect": (
        266879615,
        [
            ("ID", "id"),
            ("Flags", ("int", 0, 0)),
            ("Field_8_1_0_28440_003Max", ("int", 3, 0)),
            ("Field_8_1_0_28440_003Min", ("int", 4, 0)),
            ("Field_8_1_0_28440_005", ("int", 5, 0)),
            ("ModelCountMax", ("int", 6, 0)),
            ("ModelCountMin", ("int", 7, 0)),
            ("AttachmentPoint", ("i8", 8, 0)),
            ("SpellVisualEffectNameID", ("int", 9, 0)),
        ],
    ),
    "BeamEffect": (
        649155393,
        [
            ("ID", "id"),
            ("BeamID", ("int", 0, 0)),
            ("Flags", ("int", 3, 0)),
            ("SourceOffset", ("int", 4, 0)),
            ("DestOffset", ("int", 5, 0)),
            ("SourceAttachID", ("i8", 6, 0)),
            ("DestAttachID", ("i8", 7, 0)),
            ("SourcePositionerID", ("int", 8, 0)),
            ("DestPositionerID", ("int", 9, 0)),
        ],
    ),
    "CameraEffect": (453625693, [("ID", "id"), ("Flags", ("int", 0, 0))]),
    "CameraEffectEntry": (
        13609018,
        [
            ("ID", "id"),
            ("OrderIndex", ("u8", 0, 0)),
            ("AmplitudeCurveID", ("int", 1, 0)),
            ("Flags", ("int", 10, 0)),
            ("EffectType", ("i8", 11, 0)),
            ("DirectionType", ("u8", 12, 0)),
            ("MovementType", ("int", 13, 0)),
            ("AttenuationType", ("i8", 14, 0)),
            ("CameraEffectID", "parent"),
        ],
    ),
    "ClientSceneEffect": (
        4088582976,
        [("ID", "id"), ("SceneScriptPackageID", ("int", 0, 0))],
    ),
    "CloneEffect": (
        1707234724,
        [
            ("ID", "id"),
            ("DurationMs", ("int", 0, 0)),
            ("DelayMs", ("int", 1, 0)),
            ("FadeInTimeMs", ("int", 2, 0)),
            ("FadeOutTimeMs", ("int", 3, 0)),
            ("StateSpellVisualKitID", ("int", 4, 0)),
            ("StartSpellVisualKitID", ("int", 5, 0)),
            ("OffsetMatrixID", ("int", 6, 0)),
            ("Flags", ("int", 7, 0)),
        ],
    ),
    "CreatureDisplayInfoOption": (
        791878707,
        [
            ("ID", "id"),
            ("ChrCustomizationOptionID", ("int", 0, 0)),
            ("ChrCustomizationChoiceID", ("int", 1, 0)),
            ("CreatureDisplayInfoExtraID", "parent"),
        ],
    ),
    "DecalProperties": (
        3201398768,
        [
            ("ID", "id"),
            ("FileDataID", ("int", 0, 0)),
            ("TopTextureBlendSetID", ("int", 1, 0)),
            ("BotTextureBlendSetID", ("int", 2, 0)),
            ("Flags", ("int", 9, 0)),
            ("Priority", ("u8", 13, 0)),
            ("BlendMode", ("u8", 14, 0)),
            ("GameFlags", ("int", 15, 0)),
            ("CasterDecalPropertiesID", ("int", 16, 0)),
            ("Field_9_0_1_33978_018", ("int", 18, 0)),
            ("Field_9_0_1_33978_019", ("int", 19, 0)),
            ("Field_10_0_0_45232_020", ("int", 20, 0)),
            ("Field_11_2_0_61476_024", ("int", 24, 0)),
        ],
    ),
    "DissolveEffect": (
        1360668855,
        [
            ("ID", "id"),
            ("AttachID", ("i8", 6, 0)),
            ("ProjectionType", ("int", 7, 0)),
            ("TextureBlendSetID", ("int", 8, 0)),
            ("Flags", ("int", 10, 0)),
            ("CurveID", ("int", 11, 0)),
            ("Priority", ("int", 12, 0)),
            ("Field_10_0_0_44649_019", ("int", 19, 0)),
            ("Field_10_0_0_44649_020", ("int", 20, 0)),
        ],
    ),
    "EdgeGlowEffect": (
        3986358722,
        [
            ("ID", "id"),
            ("Flags", ("int", 9, 0)),
            ("CurveID", ("int", 11, 0)),
            ("Priority", ("int", 12, 0)),
            ("Field_12_1_0_68569_013", ("i8", 13, 0)),
        ],
    ),
    "FullScreenEffect": (
        3543812693,
        [
            ("ID", "id"),
            ("Flags", ("int", 0, 0)),
            ("OverlayTextureFileDataID", ("int", 20, 0)),
            ("EffectFadeInMs", ("int", 25, 0)),
            ("EffectFadeOutMs", ("int", 26, 0)),
            ("TextureBlendSetID", ("int", 27, 0)),
        ],
    ),
    "GradientEffect": (
        2947722316,
        [
            ("ID", "id"),
            ("Field_8_1_0_28440_014", ("int", 14, 0)),
            ("Field_8_1_0_28440_015", ("int", 15, 0)),
        ],
    ),
    "OutlineEffect": (
        3609246731,
        [
            ("ID", "id"),
            ("PassiveHighlightColorID", ("int", 0, 0)),
            ("HighlightColorID", ("int", 1, 0)),
            ("Priority", ("int", 2, 0)),
            ("Flags", ("int", 3, 0)),
            ("UnitConditionID_0", ("int", 5, 0)),
            ("UnitConditionID_1", ("int", 5, 1)),
        ],
    ),
    "RopeEffect": (
        3455316405,
        [
            ("ID", "id"),
            ("Flags", ("int", 0, 0)),
            ("Field_8_3_0_32712_001", ("i8", 1, 0)),
            ("Field_8_3_0_32712_002", ("int", 2, 0)),
            ("Field_8_3_0_32712_003", ("i8", 3, 0)),
            ("NumberOfJoints", ("int", 4, 0)),
            ("IntegrateAtJointIndex", ("int", 8, 0)),
        ],
    ),
    "ScreenEffect": (
        899921268,
        [
            ("ID", "id"),
            ("Param_0", ("int", 1, 0)),
            ("Param_1", ("int", 1, 1)),
            ("Param_2", ("int", 1, 2)),
            ("Param_3", ("int", 1, 3)),
            ("Effect", ("i8", 2, 0)),
            ("FullScreenEffectID", ("int", 3, 0)),
            ("LightParamsID", ("u16", 4, 0)),
            ("LightParamsFadeIn", ("int", 5, 0)),
            ("LightParamsFadeOut", ("int", 6, 0)),
            ("SoundAmbienceID", ("int", 7, 0)),
            ("ZoneMusicID", ("int", 8, 0)),
            ("TimeOfDayOverride", ("i16", 9, 0)),
            ("EffectMask", ("i8", 10, 0)),
            ("LightFlags", ("int", 11, 0)),
        ],
    ),
    "ScreenEffectType": (1601523272, [("ID", "id"), ("Priority", ("int", 0, 0))]),
    "ShadowyEffect": (
        784907448,
        [
            ("ID", "id"),
            ("PrimaryColor", ("int", 0, 0)),
            ("SecondaryColor", ("int", 1, 0)),
            ("AttachPos", ("i8", 6, 0)),
            ("Flags", ("int", 7, 0)),
            ("CurveID", ("int", 11, 0)),
            ("Priority", ("int", 12, 0)),
        ],
    ),
    "SoundAmbience": (
        1847973141,
        [
            ("ID", "id"),
            ("Flags", ("int", 0, 0)),
            ("SoundFilterID", ("int", 1, 0)),
            ("FlavorSoundFilterID", ("int", 2, 0)),
            ("AmbienceID_0", ("int", 3, 0)),
            ("AmbienceID_1", ("int", 3, 1)),
            ("AmbienceStartID_0", ("int", 4, 0)),
            ("AmbienceStartID_1", ("int", 4, 1)),
            ("AmbienceStopID_0", ("int", 5, 0)),
            ("AmbienceStopID_1", ("int", 5, 1)),
            ("SoundKitID_0", ("int", 6, 0)),
            ("SoundKitID_1", ("int", 6, 1)),
        ],
    ),
    "SpellChainEffects": (
        1258580565,
        [
            ("ID", "id"),
            ("SegDuration", ("int", 3, 0)),
            ("SegDelay", ("u16", 4, 0)),
            ("Flags", ("int", 5, 0)),
            ("JointCount", ("u16", 6, 0)),
            ("JointsPerMinorJoint", ("u8", 8, 0)),
            ("MinorJointsPerMajorJoint", ("u8", 9, 0)),
            ("Alpha", ("u8", 36, 0)),
            ("Red", ("u8", 37, 0)),
            ("Green", ("u8", 38, 0)),
            ("Blue", ("u8", 39, 0)),
            ("BlendMode", ("u8", 40, 0)),
            ("RenderLayer", ("u8", 41, 0)),
            ("TextureParticleFileDataID", ("int", 45, 0)),
            ("WidthScaleCurveID", ("int", 48, 0)),
            ("NumFlipFramesU", ("u8", 49, 0)),
            ("NumFlipFramesV", ("u8", 50, 0)),
            ("SoundKitID", ("int", 51, 0)),
            ("Field_11_0_0_54210_054", ("u16", 54, 0)),
            ("SpellChainEffectID_0", ("u16", 55, 0)),
            ("SpellChainEffectID_1", ("u16", 55, 1)),
            ("SpellChainEffectID_2", ("u16", 55, 2)),
            ("SpellChainEffectID_3", ("u16", 55, 3)),
            ("SpellChainEffectID_4", ("u16", 55, 4)),
            ("SpellChainEffectID_5", ("u16", 55, 5)),
            ("SpellChainEffectID_6", ("u16", 55, 6)),
            ("SpellChainEffectID_7", ("u16", 55, 7)),
            ("SpellChainEffectID_8", ("u16", 55, 8)),
            ("SpellChainEffectID_9", ("u16", 55, 9)),
            ("SpellChainEffectID_10", ("u16", 55, 10)),
            ("TextureFileDataID_0", ("int", 60, 0)),
            ("TextureFileDataID_1", ("int", 60, 1)),
            ("TextureFileDataID_2", ("int", 60, 2)),
        ],
    ),
    "SpellEffectEmission": (
        98591169,
        [("ID", "id"), ("AreaModelID", ("i16", 2, 0)), ("Flags", ("int", 3, 0))],
    ),
    "SpellProceduralEffect": (3024268161, [("ID", "id"), ("Type", ("i8", 0, 0))]),
    "SpellVisualKitAreaModel": (
        1940912356,
        [
            ("ID", "id"),
            ("ModelFileDataID", ("int", 0, 0)),
            ("Flags", ("int", 1, 0)),
            ("LifeTime", ("u16", 2, 0)),
        ],
    ),
    "SpellVisualKitDecalAttach": (
        809533799,
        [
            ("ID", "id"),
            ("SpellVisualKitID", ("int", 2, 0)),
            ("DecalPropertiesID", ("int", 3, 0)),
            ("Field_12_0_0_64741_004", ("int", 4, 0)),
            ("Field_12_0_0_64741_005", ("int", 5, 0)),
            ("Priority", ("int", 10, 0)),
            ("Field_12_0_0_64741_014", ("int", 14, 0)),
            ("SpellID", ("int", 15, 0)),
        ],
    ),
    "SpellVisualScreenEffect": (
        656712813,
        [
            ("ID", "id"),
            ("ScreenEffectID", ("int", 0, 0)),
            ("ScreenEffectTypeID", ("int", 1, 0)),
        ],
    ),
    "TextureBlendSet": (
        1251301240,
        [
            ("ID", "id"),
            ("TextureFileDataID_0", ("int", 0, 0)),
            ("TextureFileDataID_1", ("int", 0, 1)),
            ("TextureFileDataID_2", ("int", 0, 2)),
            ("SwizzleRed", ("u8", 1, 0)),
            ("SwizzleGreen", ("u8", 2, 0)),
            ("SwizzleBlue", ("u8", 3, 0)),
            ("SwizzleAlpha", ("u8", 4, 0)),
            ("Flags", ("int", 5, 0)),
        ],
    ),
    "ZoneMusic": (
        1918315781,
        [
            ("ID", "id"),
            ("SilenceIntervalMin_0", ("int", 1, 0)),
            ("SilenceIntervalMin_1", ("int", 1, 1)),
            ("SilenceIntervalMax_0", ("int", 2, 0)),
            ("SilenceIntervalMax_1", ("int", 2, 1)),
            ("Sounds_0", ("int", 3, 0)),
            ("Sounds_1", ("int", 3, 1)),
        ],
    ),
}

# Additional appearance joins, same exact Retail build/layout discipline.
CLOSURE_TABLES.update(
    {
        "ChrCustomizationCondModel": (
            0x601A4522,
            [
                ("ID", "id"),
                ("CreatureModelDataID", ("int", 0, 0)),
            ],
        ),
        "ChrCustomizationDisplayInfo": (
            0xB24CE54F,
            [
                ("ID", "id"),
                ("SpellShapeshiftFormID", ("int", 0, 0)),
                ("CreatureDisplayInfoID", ("int", 1, 0)),
            ],
        ),
        "TextureFileData": (
            0xBD7C74C2,
            [
                ("FileDataID", "id"),
                ("UsageType", ("u8", 1)),
                ("MaterialResourcesID", ("int", 2, 0)),
            ],
        ),
    }
)
